// ============================================================
// DEMO DATA — Pre-baked defect responses for sample images
// Used when DEMO_MODE is on or the API is unavailable
// ============================================================
import type { DetectionResult } from "./detect";

export const DEMO_RESULTS: Record<string, DetectionResult> = {
  "sample-1": {
    fabric_type_guess: "Grey Woven Fabric (Polyester-Cotton)",
    material: "Polyester / cotton blend",
    color: "Mid grey",
    weave_or_knit: "Plain weave",
    finish: "Piece dyed",
    metadata_confidence: 0.96,
    source: "fallback",
    image_quality: "good",
    defects: [
      {
        id: "d1",
        type: "stain",
        severity: "major",
        bbox: { x: 0.15, y: 0.2, w: 0.12, h: 0.09 },
        confidence: 0.94,
        note: "Oil stain, roughly circular, dark grey",
      },
      {
        id: "d2",
        type: "float",
        severity: "major",
        bbox: { x: 0.55, y: 0.45, w: 0.22, h: 0.03 },
        confidence: 0.88,
        note: "Warp float, 4-5 picks raised",
      },
      {
        id: "d3",
        type: "thick_yarn",
        severity: "minor",
        bbox: { x: 0.3, y: 0.7, w: 0.08, h: 0.12 },
        confidence: 0.76,
        note: "Thick warp yarn, slight texture raise",
      },
    ],
  },
  "sample-2": {
    fabric_type_guess: "Indigo Denim (Cotton Twill)",
    material: "100% cotton",
    color: "Indigo blue",
    weave_or_knit: "3/1 twill",
    finish: "Rinsed denim",
    metadata_confidence: 0.98,
    source: "fallback",
    image_quality: "good",
    defects: [
      {
        id: "d1",
        type: "slub",
        severity: "major",
        bbox: { x: 0.25, y: 0.15, w: 0.18, h: 0.06 },
        confidence: 0.91,
        note: "Slub cluster in warp, pronounced thick-thin variation",
      },
      {
        id: "d2",
        type: "broken_end",
        severity: "major",
        bbox: { x: 0.6, y: 0.55, w: 0.04, h: 0.25 },
        confidence: 0.85,
        note: "Single broken warp end, visible gap in twill structure",
      },
      {
        id: "d3",
        type: "stain",
        severity: "minor",
        bbox: { x: 0.1, y: 0.8, w: 0.07, h: 0.07 },
        confidence: 0.72,
        note: "Light sizing stain, may wash out",
      },
    ],
  },
  "sample-3": {
    fabric_type_guess: "White Shirting (Cotton Plain Weave)",
    material: "100% cotton",
    color: "Optical white",
    weave_or_knit: "Plain weave",
    finish: "Easy-care shirting finish",
    metadata_confidence: 0.97,
    source: "fallback",
    image_quality: "good",
    defects: [
      {
        id: "d1",
        type: "weft_bar",
        severity: "major",
        bbox: { x: 0.0, y: 0.38, w: 1.0, h: 0.06 },
        confidence: 0.97,
        note: "Full-width weft bar, visible density change across fabric",
      },
      {
        id: "d2",
        type: "thin_place",
        severity: "minor",
        bbox: { x: 0.42, y: 0.62, w: 0.14, h: 0.04 },
        confidence: 0.78,
        note: "Thin weft region, slight transparency variation",
      },
    ],
  },
  "sample-4": {
    fabric_type_guess: "Grey Jersey Knit (Cotton Single Jersey)",
    material: "100% cotton",
    color: "Heather grey",
    weave_or_knit: "Single jersey knit",
    finish: "Softener finish",
    metadata_confidence: 0.95,
    source: "fallback",
    image_quality: "good",
    defects: [
      {
        id: "d1",
        type: "hole",
        severity: "major",
        bbox: { x: 0.38, y: 0.28, w: 0.06, h: 0.06 },
        confidence: 0.99,
        note: "Run hole, 3-4 course drop, visible through",
      },
      {
        id: "d2",
        type: "crease",
        severity: "major",
        bbox: { x: 0.0, y: 0.6, w: 1.0, h: 0.08 },
        confidence: 0.89,
        note: "Full-width crease mark from improper roll storage",
      },
      {
        id: "d3",
        type: "stain",
        severity: "minor",
        bbox: { x: 0.7, y: 0.15, w: 0.09, h: 0.06 },
        confidence: 0.68,
        note: "Faint lubricant trace, minor",
      },
    ],
  },
};
